package com.fl.order.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TBasedata implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_ID
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private BigDecimal fId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_CODE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_NAME
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_GROUP
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_ISGROUP
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fIsgroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_CREATE_BY
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fCreateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_CREATE_DATE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_UPDATE_BY
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_STATUS
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_VERSION
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private BigDecimal fVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_STEPID
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fStepid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_WERKS
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fWerks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_REMARK
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_BASEDATA.F_ACTIVE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private String fActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_BASEDATA
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_ID
     *
     * @return the value of T_BASEDATA.F_ID
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public BigDecimal getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_ID
     *
     * @param fId the value for T_BASEDATA.F_ID
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfId(BigDecimal fId) {
        this.fId = fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_CODE
     *
     * @return the value of T_BASEDATA.F_CODE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfCode() {
        return fCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_CODE
     *
     * @param fCode the value for T_BASEDATA.F_CODE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfCode(String fCode) {
        this.fCode = fCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_NAME
     *
     * @return the value of T_BASEDATA.F_NAME
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfName() {
        return fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_NAME
     *
     * @param fName the value for T_BASEDATA.F_NAME
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfName(String fName) {
        this.fName = fName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_GROUP
     *
     * @return the value of T_BASEDATA.F_GROUP
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfGroup() {
        return fGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_GROUP
     *
     * @param fGroup the value for T_BASEDATA.F_GROUP
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfGroup(String fGroup) {
        this.fGroup = fGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_ISGROUP
     *
     * @return the value of T_BASEDATA.F_ISGROUP
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfIsgroup() {
        return fIsgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_ISGROUP
     *
     * @param fIsgroup the value for T_BASEDATA.F_ISGROUP
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfIsgroup(String fIsgroup) {
        this.fIsgroup = fIsgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_CREATE_BY
     *
     * @return the value of T_BASEDATA.F_CREATE_BY
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfCreateBy() {
        return fCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_CREATE_BY
     *
     * @param fCreateBy the value for T_BASEDATA.F_CREATE_BY
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfCreateBy(String fCreateBy) {
        this.fCreateBy = fCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_CREATE_DATE
     *
     * @return the value of T_BASEDATA.F_CREATE_DATE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfCreateDate() {
        return fCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_CREATE_DATE
     *
     * @param fCreateDate the value for T_BASEDATA.F_CREATE_DATE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfCreateDate(String fCreateDate) {
        this.fCreateDate = fCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_UPDATE_BY
     *
     * @return the value of T_BASEDATA.F_UPDATE_BY
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfUpdateBy() {
        return fUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_UPDATE_BY
     *
     * @param fUpdateBy the value for T_BASEDATA.F_UPDATE_BY
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfUpdateBy(String fUpdateBy) {
        this.fUpdateBy = fUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_UPDATE_DATE
     *
     * @return the value of T_BASEDATA.F_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfUpdateDate() {
        return fUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_UPDATE_DATE
     *
     * @param fUpdateDate the value for T_BASEDATA.F_UPDATE_DATE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfUpdateDate(String fUpdateDate) {
        this.fUpdateDate = fUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_STATUS
     *
     * @return the value of T_BASEDATA.F_STATUS
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfStatus() {
        return fStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_STATUS
     *
     * @param fStatus the value for T_BASEDATA.F_STATUS
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfStatus(String fStatus) {
        this.fStatus = fStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_VERSION
     *
     * @return the value of T_BASEDATA.F_VERSION
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public BigDecimal getfVersion() {
        return fVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_VERSION
     *
     * @param fVersion the value for T_BASEDATA.F_VERSION
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfVersion(BigDecimal fVersion) {
        this.fVersion = fVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_STEPID
     *
     * @return the value of T_BASEDATA.F_STEPID
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfStepid() {
        return fStepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_STEPID
     *
     * @param fStepid the value for T_BASEDATA.F_STEPID
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfStepid(String fStepid) {
        this.fStepid = fStepid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_WERKS
     *
     * @return the value of T_BASEDATA.F_WERKS
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfWerks() {
        return fWerks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_WERKS
     *
     * @param fWerks the value for T_BASEDATA.F_WERKS
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfWerks(String fWerks) {
        this.fWerks = fWerks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_REMARK
     *
     * @return the value of T_BASEDATA.F_REMARK
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfRemark() {
        return fRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_REMARK
     *
     * @param fRemark the value for T_BASEDATA.F_REMARK
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfRemark(String fRemark) {
        this.fRemark = fRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_BASEDATA.F_ACTIVE
     *
     * @return the value of T_BASEDATA.F_ACTIVE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public String getfActive() {
        return fActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_BASEDATA.F_ACTIVE
     *
     * @param fActive the value for T_BASEDATA.F_ACTIVE
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    public void setfActive(String fActive) {
        this.fActive = fActive;
    }
}