package com.fl.order.dao.mapper;

import com.fl.order.model.TBasedata;
import java.math.BigDecimal;
import java.util.List;

public interface TBasedataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASEDATA
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASEDATA
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    int insert(TBasedata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASEDATA
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    TBasedata selectByPrimaryKey(BigDecimal fId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASEDATA
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    List<TBasedata> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_BASEDATA
     *
     * @mbggenerated Wed Apr 06 20:11:30 CST 2016
     */
    int updateByPrimaryKey(TBasedata record);
}